### PR TITLE
Support for .cat TLD domains

### PR DESCRIPTION
**Pull request by franciscoj**
Hi, 

I've added support for .cat TLD domains on Authentication.domain_tld_regex. See http://www.domini.cat/en_index.html for more info.

Kind regards,
Francisco.

### CODE REVIEW

**Comment by jsanders** [comment]
I know this is pretty old, but I'm wondering if anyone can comment on the logic behind listing out all supported tlds with more than 2 characters, rather than using something like "(?:[A-Z]{2,})" for the expression. Is there something horrible about that solution that I'm not seeing?

**Comment by hakanai** [comment]
I'm not convinced that anyone is looking at the issues on this project, but in case someone does end up here, I raised a very similar ticket on someone else's fork, only I didn't just fix it for .cat - https://github.com/jeremydurham/restful-authentication/pull/1

**Comment by franciscoj** [comment]
I don't think this will get integrated after 3 years, so I'm closing it :P

**Comment by hakanai** [comment]
Well, as long as someone makes the obvious alternative improvement of just not restricting the TLD at all, I wouldn't object. (Incidentally, I didn't find it for .cat, there was some other domain a customer was actually using.)

**Pull request closed without merging**
